name: date_field
description: Contains DateField and DateFormField
version: 0.0.1
homepage: 'https://github.com/GaspardMerten/date_field'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  flutter:
    sdk: flutter
