name: date_field
description: A field widget to allow users to select a date using platforms date picker dialogs.
version: 5.2.0
homepage: 'https://github.com/GaspardMerten/date_field'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: '>=0.18.0 <0.20.0'