name: date_field
description: A widget in the form of a field that lets people enter choose a date/time/date and time via a date/time picker dialog.
version: 1.0.1
homepage: 'https://github.com/GaspardMerten/date_field'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ">=0.2.7 <2.0.0"

