name: date_field
description: A widget in the form of a field that lets people choose a date, a time or both.
version: 1.0.5
homepage: 'https://github.com/GaspardMerten/date_field'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ">=0.2.7 <5.0.0"

